spring:
    datasource:
        platform: h2
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: ''
server:
    error:
        whitelabel:
            enabled: false
logging:
    level:
        # These packages contain logs for @Bean registration
        org.springframework.core.io.support: DEBUG
        org.springframework.context.annotation: DEBUG
